version: '3.1'
services:
  nodejs-app:
    build: .
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    ports:
      - "3000:3000"
    networks:
      - my_network
  caddy:
    image: caddy:2.7.6
    container_name: caddy
    hostname: caddy
    restart: unless-stopped
    ports:
      - "443:443"
   # env_file:
   #   - ./.env
    tty: true
    depends_on:
      - nodejs-app
    networks:
      - my_network
volumes:
  caddy_data:
  caddy_config:
networks:
  my_network: