services:
  app:
    build:
      context: .
      args:
        - DB_DATABASE
        - DB_HOST
        - DB_PASSWORD
        - DB_USER
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_DATABASE}
      - NODE_ENV=development
      - DEBUG=puppeteer:*
    container_name: cyprus-bus
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"