services:
  nodejs-app:
    build:
      context: .
      args:
        - DB_DATABASE
        - DB_HOST
        - DB_PASSWORD
        - DB_USER
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    ports:
      - "3000:3000"
    networks:
      - my_network
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE}
      - NODE_ENV=development


  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

networks:
  my_network:

volumes:
  pgdata: