services:
  nodejs-app:
    build:
      context: .
      args:
        - DB_DATABASE
        - DB_HOST
        - DB_PASSWORD
        - DB_USER
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_DATABASE}
      - NODE_ENV=development

# Networks and volumes sections removed as they're no longer needed